//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lang {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LP() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lang.LP", typeof(LP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add DPS server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddDpsServer {
            get {
                return ResourceManager.GetString("AddDpsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Aggro {
            get {
                return ResourceManager.GetString("Aggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggro time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Aggro_Time {
            get {
                return ResourceManager.GetString("Aggro_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Time holding boss aggro&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Aggro_Time_Tooltip {
            get {
                return ResourceManager.GetString("Aggro_Time_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aggro take count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Aggro_Tooltip {
            get {
                return ResourceManager.GetString("Aggro_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alliance color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllianceColor {
            get {
                return ResourceManager.GetString("AllianceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed area url과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllowedAreaUrl {
            get {
                return ResourceManager.GetString("AllowedAreaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    probably is already in use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlreadyInUse {
            get {
                return ResourceManager.GetString("AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to update the application?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string App_Do_you_want_to_update {
            get {
                return ResourceManager.GetString("App_Do_you_want_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to contact update server, try again later, additional data available in error.log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string App_Unable_to_contact_update_server {
            get {
                return ResourceManager.GetString("App_Unable_to_contact_update_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string App_Update_Available {
            get {
                return ResourceManager.GetString("App_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   apply to your party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplyToYourParty {
            get {
                return ResourceManager.GetString("ApplyToYourParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AreaColor {
            get {
                return ResourceManager.GetString("AreaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AuthToken {
            get {
                return ResourceManager.GetString("AuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatically disable on heavy load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoDisableChatWhenOverloaded {
            get {
                return ResourceManager.GetString("AutoDisableChatWhenOverloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avg crit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AverageCrit {
            get {
                return ResourceManager.GetString("AverageCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avg DPS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AvgDPS {
            get {
                return ResourceManager.GetString("AvgDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avg white과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AvgWhite {
            get {
                return ResourceManager.GetString("AvgWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bad server url과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bad_server_url {
            get {
                return ResourceManager.GetString("Bad_server_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Berserker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Berserker {
            get {
                return ResourceManager.GetString("Berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blur player names과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Blur_player_names {
            get {
                return ResourceManager.GetString("Blur_player_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boss과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boss HP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BossHP {
            get {
                return ResourceManager.GetString("BossHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brawler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Brawler {
            get {
                return ResourceManager.GetString("Brawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Buff {
            get {
                return ResourceManager.GetString("Buff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CaptureMode {
            get {
                return ResourceManager.GetString("CaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chained과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Chained {
            get {
                return ResourceManager.GetString("Chained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Class과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close (no confirm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseNoConfirm {
            get {
                return ResourceManager.GetString("CloseNoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   s CMA DPS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMADPS {
            get {
                return ResourceManager.GetString("CMADPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat ready check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CombatReadyCheck {
            get {
                return ResourceManager.GetString("CombatReadyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact try과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContactTry {
            get {
                return ResourceManager.GetString("ContactTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy &quot;/inspect Name&quot; on party apply request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyInspect {
            get {
                return ResourceManager.GetString("CopyInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill Сasts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % Crit Dmg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CritDamagePercent {
            get {
                return ResourceManager.GetString("CritDamagePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Critical과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % Crit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CritPercent {
            get {
                return ResourceManager.GetString("CritPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crits과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Crits {
            get {
                return ResourceManager.GetString("Crits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damage done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Damage_done {
            get {
                return ResourceManager.GetString("Damage_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % Dmg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DamagePercent {
            get {
                return ResourceManager.GetString("DamagePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dmg taken과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DamgeTaken {
            get {
                return ResourceManager.GetString("DamgeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Death time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Death_Time {
            get {
                return ResourceManager.GetString("Death_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Time spent on the floor&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Death_Time_Tooltip {
            get {
                return ResourceManager.GetString("Death_Time_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deaths과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deaths count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Deaths_Tooltip {
            get {
                return ResourceManager.GetString("Deaths_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay to wait when pasting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DelayToWaitPasting {
            get {
                return ResourceManager.GetString("DelayToWaitPasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable party events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisablePartyEvents {
            get {
                return ResourceManager.GetString("DisablePartyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display only boss hit by meter user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Display_only_boss_hit_by_meter_user {
            get {
                return ResourceManager.GetString("Display_only_boss_hit_by_meter_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer based on aggro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Display_timer_aggro_or_firsthit {
            get {
                return ResourceManager.GetString("Display_timer_aggro_or_firsthit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dps {
            get {
                return ResourceManager.GetString("Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DPS upload url과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DpsUploadUrl {
            get {
                return ResourceManager.GetString("DpsUploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eff Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EffectTime {
            get {
                return ResourceManager.GetString("EffectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emotes color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EmotesColor {
            get {
                return ResourceManager.GetString("EmotesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable chat and notification functions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableChat {
            get {
                return ResourceManager.GetString("EnableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableOverlay {
            get {
                return ResourceManager.GetString("EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableRealtimeGraph {
            get {
                return ResourceManager.GetString("EnableRealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable discord&apos;s Rich Presence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableRp {
            get {
                return ResourceManager.GetString("EnableRp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enrage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enrage {
            get {
                return ResourceManager.GetString("Enrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_archer {
            get {
                return ResourceManager.GetString("events_archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///  &lt;!-- Unleash ubreakable --&gt;
        ///    &lt;abnormality ingame=&quot;true&quot; trigger=&quot;Ending&quot; target=&quot;Self&quot; remaining_seconds_before_trigger=&quot;3&quot; rewarn_timeout_seconds=&quot;2&quot;&gt;
        ///        &lt;abnormalities&gt;
        ///            &lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///        &lt;/abnormalities&gt;
        ///        &lt;actions&gt;
        ///            &lt;notify&gt;
        ///                &lt;text_to_speech text=&quot;Die Die Die&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot; voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///            &lt;/notify&gt;
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_berserker {
            get {
                return ResourceManager.GetString("events_berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;	
        ///	&lt;!-- Endurance debuff  --&gt;
        ///	&lt;abnormality active=&quot;false&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Boss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;10153140&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_brawler {
            get {
                return ResourceManager.GetString("events_brawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///
        ///	&lt;!-- Adrenaline Rush --&gt;
        ///	&lt;abnormality active=&quot;true&quot; ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Self&quot; ignore_classes=&quot;Mystic,Priest&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;200701&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200700&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Female&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;80&quot; rate=&quot;+3&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnormality&gt;
        ///	
        ///	&lt;!-- P[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_common {
            get {
                return ResourceManager.GetString("events_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///		
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_gunner {
            get {
                return ResourceManager.GetString("events_gunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;	
        ///	&lt;!-- Endurance debuff --&gt;
        ///	&lt;abnormality active=&quot;true&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Boss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;3000&quot; /[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_lancer {
            get {
                return ResourceManager.GetString("events_lancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///
        ///	&lt;!-- Unleash berserker --&gt;
        ///	&lt;abnormality ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Party&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;1000&quot; /&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnor[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_mystic {
            get {
                return ResourceManager.GetString("events_mystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	&lt;!-- Focus --&gt;
        ///	&lt;abnormality active=&quot;true&quot; rewarn_timeout_seconds=&quot;3&quot; ingame=&quot;true&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Self&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;10154030&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;text_to_speech text=&quot;Focus&quot; voice_gender=&quot;Female&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;80&quot; rate=&quot;+3&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnormality&gt;
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_ninja {
            get {
                return ResourceManager.GetString("events_ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	
        ///	
        ///	&lt;!-- Unleash berserker --&gt;
        ///	&lt;abnormality ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Party&quot; ignore_classes=&quot;Berserker&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;1000&quot; /&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot; voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///			&lt;/[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_priest {
            get {
                return ResourceManager.GetString("events_priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_reaper {
            get {
                return ResourceManager.GetString("events_reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///  &lt;!-- Notifies for missing overpower buff--&gt;
        ///    &lt;abnormality ingame=&quot;true&quot; remaining_seconds_before_trigger=&quot;10&quot; rewarn_timeout_seconds=&quot;3&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Self&quot;&gt;
        ///        &lt;abnormalities&gt;
        ///            &lt;abnormality&gt;300330&lt;/abnormality&gt;
        ///        &lt;/abnormalities&gt;
        ///        &lt;actions&gt;
        ///            &lt;notify&gt;
        ///                &lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{player_name} {time_left}&quot; display_time=&quot;3000&quot; /&gt;
        ///         [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_slayer {
            get {
                return ResourceManager.GetString("events_slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_sorcerer {
            get {
                return ResourceManager.GetString("events_sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_valkyrie {
            get {
                return ResourceManager.GetString("events_valkyrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	
        ///	&lt;!-- Endurance debuff --&gt;
        ///	&lt;abnormality active=&quot;false&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;MyBoss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;101200&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;101220&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;10153140&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;a[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string events_warrior {
            get {
                return ResourceManager.GetString("events_warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export current과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportCurrent {
            get {
                return ResourceManager.GetString("ExportCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export packets logs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportPacketLogs {
            get {
                return ResourceManager.GetString("ExportPacketLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fight {
            get {
                return ResourceManager.GetString("Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fight Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fight_Duration {
            get {
                return ResourceManager.GetString("Fight_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % Fight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FightPercent {
            get {
                return ResourceManager.GetString("FightPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format paste string과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FormatPasteString {
            get {
                return ResourceManager.GetString("FormatPasteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Front과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GeneralColor {
            get {
                return ResourceManager.GetString("GeneralColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glyph upload url과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GlyphUploadURL {
            get {
                return ResourceManager.GetString("GlyphUploadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guild color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GuildColor {
            get {
                return ResourceManager.GetString("GuildColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gunner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Gunner {
            get {
                return ResourceManager.GetString("Gunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heal Crit %과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HealCritPercent {
            get {
                return ResourceManager.GetString("HealCritPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hits과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hits taken과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HitsTaken {
            get {
                return ResourceManager.GetString("HitsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hit/m과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HPM {
            get {
                return ResourceManager.GetString("HPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle reset timeout in sec (0=disable)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IdleResetTimeout {
            get {
                return ResourceManager.GetString("IdleResetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual dps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Individual_dps {
            get {
                return ResourceManager.GetString("Individual_dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JoyOfPartying 100%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string JoyOfPartying {
            get {
                return ResourceManager.GetString("JoyOfPartying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lancer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lancer {
            get {
                return ResourceManager.GetString("Lancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lvl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lvl {
            get {
                return ResourceManager.GetString("Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boss + Adds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWindow_Boss_Adds {
            get {
                return ResourceManager.GetString("MainWindow_Boss_Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Shinra Meter V과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWindow_Close_Shinra_Meter_V {
            get {
                return ResourceManager.GetString("MainWindow_Close_Shinra_Meter_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close the application?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWindow_Do_you_want_to_close_the_application {
            get {
                return ResourceManager.GetString("MainWindow_Do_you_want_to_close_the_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An fatal error has be found, please see the error.log file for more information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWindow_Fatal_error {
            get {
                return ResourceManager.GetString("MainWindow_Fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only boss과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainWindow_Only_boss {
            get {
                return ResourceManager.GetString("MainWindow_Only_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max crit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaxCrit {
            get {
                return ResourceManager.GetString("MaxCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TTS max size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaxTTSSize {
            get {
                return ResourceManager.GetString("MaxTTSSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max white과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaxWhite {
            get {
                return ResourceManager.GetString("MaxWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Crit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinCrit {
            get {
                return ResourceManager.GetString("MinCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mot {
            get {
                return ResourceManager.GetString("Mot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute sound과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MuteSound {
            get {
                return ResourceManager.GetString("MuteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mystic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mystic {
            get {
                return ResourceManager.GetString("Mystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ninja과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ninja {
            get {
                return ResourceManager.GetString("Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No active quest at the moment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No_active_quest {
            get {
                return ResourceManager.GetString("No_active_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable abnormality icons under HP bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoAbnormalsInHUD {
            get {
                return ResourceManager.GetString("NoAbnormalsInHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CrystalBind missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoCrystalBind {
            get {
                return ResourceManager.GetString("NoCrystalBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable ingame chat paste과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoPaste {
            get {
                return ResourceManager.GetString("NoPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify about CrystalBinds.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyCB {
            get {
                return ResourceManager.GetString("NotifyCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of players displayed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NumberPlayersDisplayed {
            get {
                return ResourceManager.GetString("NumberPlayersDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offered price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OfferedPrice {
            get {
                return ResourceManager.GetString("OfferedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open chat box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenChatBox {
            get {
                return ResourceManager.GetString("OpenChatBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Party invite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PartyInvite {
            get {
                return ResourceManager.GetString("PartyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Party matching success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PartyMatchingSuccess {
            get {
                return ResourceManager.GetString("PartyMatchingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /s과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PerSecond {
            get {
                return ResourceManager.GetString("PerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popup stay active for X ms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupStayActiveForXms {
            get {
                return ResourceManager.GetString("PopupStayActiveForXms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private channel color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrivateChannelColor {
            get {
                return ResourceManager.GetString("PrivateChannelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quests done status: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quests_status {
            get {
                return ResourceManager.GetString("Quests_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raid color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RaidColor {
            get {
                return ResourceManager.GetString("RaidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealtimeGraphAnimated {
            get {
                return ResourceManager.GetString("RealtimeGraphAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CMA seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealtimeGraphCmaSeconds {
            get {
                return ResourceManager.GetString("RealtimeGraphCmaSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displayed interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealtimeGraphDisplayedInterval {
            get {
                return ResourceManager.GetString("RealtimeGraphDisplayedInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RealtimeGraphMode {
            get {
                return ResourceManager.GetString("RealtimeGraphMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reaper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reaper {
            get {
                return ResourceManager.GetString("Reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn’t register the hot key.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterHotKeyError {
            get {
                return ResourceManager.GetString("RegisterHotKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove DPS server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveDpsServer {
            get {
                return ResourceManager.GetString("RemoveDpsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Tera alt+enter hotkey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveTeraAltEnterHotkey {
            get {
                return ResourceManager.GetString("RemoveTeraAltEnterHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RichPresenceShowCharacter {
            get {
                return ResourceManager.GetString("RichPresenceShowCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RichPresenceShowLocation {
            get {
                return ResourceManager.GetString("RichPresenceShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RichPresenceShowParty {
            get {
                return ResourceManager.GetString("RichPresenceShowParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RichPresenceShowStatus {
            get {
                return ResourceManager.GetString("RichPresenceShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lvl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpLevel {
            get {
                return ResourceManager.GetString("RpLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Various과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpMultipleEnemies {
            get {
                return ResourceManager.GetString("RpMultipleEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BG Queue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpPartyBg {
            get {
                return ResourceManager.GetString("RpPartyBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpPartyParty {
            get {
                return ResourceManager.GetString("RpPartyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpPartyQueue {
            get {
                return ResourceManager.GetString("RpPartyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In raid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpPartyRaid {
            get {
                return ResourceManager.GetString("RpPartyRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpPartySolo {
            get {
                return ResourceManager.GetString("RpPartySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In battleground matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusBattlegroundMatch {
            get {
                return ResourceManager.GetString("RpStatusBattlegroundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusCharSelect {
            get {
                return ResourceManager.GetString("RpStatusCharSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In dungeon matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusDungeonMatch {
            get {
                return ResourceManager.GetString("RpStatusDungeonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusFight {
            get {
                return ResourceManager.GetString("RpStatusFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusIdle {
            get {
                return ResourceManager.GetString("RpStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LFG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusLfg {
            get {
                return ResourceManager.GetString("RpStatusLfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RpStatusPlaying {
            get {
                return ResourceManager.GetString("RpStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Say color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SayColor {
            get {
                return ResourceManager.GetString("SayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   s과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seller price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SellerPrice {
            get {
                return ResourceManager.GetString("SellerPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ###########################################################
        ///# Add additional servers in this file (needed only for
        ///# VPN/Proxy that is not supported out-of-box)
        ///#
        ///# Format must follow the format IP Region ServerName
        ///#
        ///# Example:
        ///# 111.22.33.44 NA VPN Server 1
        ///#
        ///# Current possible regions: EU, NA, RU, KR, KR-PTS, TW, THA, JP, JP-C
        ///#
        ///# Lines starting with &apos;#&apos; are ignored
        ///# Place servers below the next line
        ///###########################################################과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerOverrides {
            get {
                return ResourceManager.GetString("ServerOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chat color settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_ChatColors {
            get {
                return ResourceManager.GetString("SettingsTab_ChatColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detection settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Detection {
            get {
                return ResourceManager.GetString("SettingsTab_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discord presence settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_DiscordRP {
            get {
                return ResourceManager.GetString("SettingsTab_DiscordRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Events {
            get {
                return ResourceManager.GetString("SettingsTab_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realtime graph settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Graph {
            get {
                return ResourceManager.GetString("SettingsTab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Home {
            get {
                return ResourceManager.GetString("SettingsTab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HP bar settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_HPBar {
            get {
                return ResourceManager.GetString("SettingsTab_HPBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input and hotkeys settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Input {
            get {
                return ResourceManager.GetString("SettingsTab_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Layout {
            get {
                return ResourceManager.GetString("SettingsTab_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misc settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Misc {
            get {
                return ResourceManager.GetString("SettingsTab_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Servers settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_Servers {
            get {
                return ResourceManager.GetString("SettingsTab_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TTS settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_TTS {
            get {
                return ResourceManager.GetString("SettingsTab_TTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTab_UI {
            get {
                return ResourceManager.GetString("SettingsTab_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show common_afk events ingame과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowAfkEventsIngame {
            get {
                return ResourceManager.GetString("ShowAfkEventsIngame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Boss HP Bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowBossGage {
            get {
                return ResourceManager.GetString("ShowBossGage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show self on top position in UI과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShowSelfOnTop {
            get {
                return ResourceManager.GetString("ShowSelfOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Side {
            get {
                return ResourceManager.GetString("Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SkillDealt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkillDealt {
            get {
                return ResourceManager.GetString("SkillDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SkillReceived과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkillReceived {
            get {
                return ResourceManager.GetString("SkillReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slayer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Slayer {
            get {
                return ResourceManager.GetString("Slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slaying과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Slaying {
            get {
                return ResourceManager.GetString("Slaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Slaying&apos; crystal is working (if equipped) when player in this state.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SlayingTooltip {
            get {
                return ResourceManager.GetString("SlayingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorcerer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sorcerer {
            get {
                return ResourceManager.GetString("Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to another sound system과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SoundConsoleBeepFallback {
            get {
                return ResourceManager.GetString("SoundConsoleBeepFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound filename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SoundFilename {
            get {
                return ResourceManager.GetString("SoundFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound stay active for X ms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SoundStayActiveForXms {
            get {
                return ResourceManager.GetString("SoundStayActiveForXms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound volume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Action {
            get {
                return ResourceManager.GetString("SystemTray_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_AddServer {
            get {
                return ResourceManager.GetString("SystemTray_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autoexport to Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Autoexport_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Autoexport_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autoexport to JSON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Autoexport_to_Json {
            get {
                return ResourceManager.GetString("SystemTray_Autoexport_to_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   before crash과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_before_crash {
            get {
                return ResourceManager.GetString("SystemTray_before_crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings are saved when closing this window and when closing meter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Bottom_Text {
            get {
                return ResourceManager.GetString("SystemTray_Bottom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click throu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Click_throu {
            get {
                return ResourceManager.GetString("SystemTray_Click_throu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Colors {
            get {
                return ResourceManager.GetString("SystemTray_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Colors_Background {
            get {
                return ResourceManager.GetString("SystemTray_Colors_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Colors_Border {
            get {
                return ResourceManager.GetString("SystemTray_Colors_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Colors_Player {
            get {
                return ResourceManager.GetString("SystemTray_Colors_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Config {
            get {
                return ResourceManager.GetString("SystemTray_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count only bosses과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Count_only_bosses {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count only party members과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Count_only_party_members {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_party_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect bosses by HP bar (ignore db)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Detect_bosses_by_HP_bar {
            get {
                return ResourceManager.GetString("SystemTray_Detect_bosses_by_HP_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discord과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Discord {
            get {
                return ResourceManager.GetString("SystemTray_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel: calc moving average DPS for X seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_ExcelCMADPSSeconds {
            get {
                return ResourceManager.GetString("SystemTray_ExcelCMADPSSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Export_current_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to JSON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Export_current_to_Json {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to site과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Export_current_to_Site {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore packets threshold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_IgnorePacketsThreshold {
            get {
                return ResourceManager.GetString("SystemTray_IgnorePacketsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invisible when no stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Invisible_when_no_stats {
            get {
                return ResourceManager.GetString("SystemTray_Invisible_when_no_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Links과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Links {
            get {
                return ResourceManager.GetString("SystemTray_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low process priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_LowPriority {
            get {
                return ResourceManager.GetString("SystemTray_LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main window opacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_MainWindowOpacity {
            get {
                return ResourceManager.GetString("SystemTray_MainWindowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_No_server {
            get {
                return ResourceManager.GetString("SystemTray_No_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other windows opacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_OtherWindowOpacity {
            get {
                return ResourceManager.GetString("SystemTray_OtherWindowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Packets waiting to be processed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Packet_waiting {
            get {
                return ResourceManager.GetString("SystemTray_Packet_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patch note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Patch_note {
            get {
                return ResourceManager.GetString("SystemTray_Patch_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Performance_information {
            get {
                return ResourceManager.GetString("SystemTray_Performance_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report issue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Report_issue {
            get {
                return ResourceManager.GetString("SystemTray_Report_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Scale {
            get {
                return ResourceManager.GetString("SystemTray_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show always과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Show_always {
            get {
                return ResourceManager.GetString("SystemTray_Show_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show realtime graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_ShowGraph {
            get {
                return ResourceManager.GetString("SystemTray_ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Site export history과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Site_export {
            get {
                return ResourceManager.GetString("SystemTray_Site_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snap windows to borders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_SnapToBorders {
            get {
                return ResourceManager.GetString("SystemTray_SnapToBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stay topmost과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Stay_topmost {
            get {
                return ResourceManager.GetString("SystemTray_Stay_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use npcap (requires restart)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Use_Npcap {
            get {
                return ResourceManager.GetString("SystemTray_Use_Npcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiki과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemTray_Wiki {
            get {
                return ResourceManager.GetString("SystemTray_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Api error or timeout.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TeraDpsIoApiError {
            get {
                return ResourceManager.GetString("TeraDpsIoApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test sound과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestSound {
            get {
                return ResourceManager.GetString("TestSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time sync error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Time_sync_error {
            get {
                return ResourceManager.GetString("Time_sync_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOTAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TotalEncounter {
            get {
                return ResourceManager.GetString("TotalEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trading {
            get {
                return ResourceManager.GetString("Trading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trading color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TradingColor {
            get {
                return ResourceManager.GetString("TradingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Truncate TTS message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TTSSizeExceededTruncate {
            get {
                return ResourceManager.GetString("TTSSizeExceededTruncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get key from string과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unable_to_get_key_from_string {
            get {
                return ResourceManager.GetString("Unable_to_get_key_from_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown client version, meter require update to continue working: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unknown_client_version {
            get {
                return ResourceManager.GetString("Unknown_client_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload glyph build과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploadGlyphBuild {
            get {
                return ResourceManager.GetString("UploadGlyphBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused by user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserPaused {
            get {
                return ResourceManager.GetString("UserPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valkyrie과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Valkyrie {
            get {
                return ResourceManager.GetString("Valkyrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vanguard credits are close to cap:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VanguardCredits {
            get {
                return ResourceManager.GetString("VanguardCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for map change or relog과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaitingMapChange {
            get {
                return ResourceManager.GetString("WaitingMapChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warrior과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Warrior {
            get {
                return ResourceManager.GetString("Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whisper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Whisper {
            get {
                return ResourceManager.GetString("Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whisper color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WhisperColor {
            get {
                return ResourceManager.GetString("WhisperColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your computer is too slow to use this DPS meter.
        ///Can&apos;t analyse all those packet in decent amount of time. 
        ///Reset and paused until map change or relog.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Your_computer_is_too_slow {
            get {
                return ResourceManager.GetString("Your_computer_is_too_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your hotkeys.xml file is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Your_hotkeys_xml_file_is_invalid {
            get {
                return ResourceManager.GetString("Your_hotkeys_xml_file_is_invalid", resourceCulture);
            }
        }
    }
}
